### ISSUE TITLE
It stopped crafting stuff. 

### ISSUE THREAD

**Issue by qwertgfda** [dandcvs/KGAutoPlay#1]
It doesn't craft stuff anymore. 
Message in console:

kitg.js:563 Uncaught TypeError: Cannot set property 'innerText' of undefined
    at autoCraft2 (VM137 kitg.js:563)

**Comment by dandcvs** [comment]
Which browser are you using?

**Comment by qwertgfda** [comment]
I'm using google chrome, I tried in firefox also, had it didn't craft stuff for me there either. 

Before you change soemthing in AutoCraft2 the other day it worked fine.

**Comment by dandcvs** [comment]
Try it now.

**Comment by qwertgfda** [comment]
Still not working in firefox, don't really wanna try on chrome, since I don't wanna make my alicorns into RC then relics.

I think the crafting not working have to doing with the changes on https://github.com/dandcvs/KGAutoPlay/commit/0c5d3edf2db6849793b5e8b4b6ede5775a07b736

(side note: 
Would be a great with an options for both not refining Alicorns, and relics since there would be really good reason to not make alicorns into Timecrystals right away, and really good to not make all your time crystals into relics. same with building chronosphere before u planning on resetting.)

**Comment by dandcvs** [comment]
Now you have same Message in console?

**Comment by qwertgfda** [comment]
Still not working, got another error message now: 
Uncaught TypeError: Cannot read property 'children' of undefined
    at autoCraft2 (kitg.js:565)

**Comment by dandcvs** [comment]
i think problim in  "Color schemes" in game options, each color scheme has unic xpath links. i will fix it soon.

And I'll think about it:
(
Would be a great with an options for both not refining Alicorns, and relics since there would be really good reason to not make alicorns into Timecrystals right away, and really good to not make all your time crystals into relics. same with building chronosphere before u planning on resetting.)

**Comment by Danik2212** [comment]
Good find. Which color theme are you using? The basic white one?

**Comment by dandcvs** [comment]
Im using standard white theme.
1. change theme on white standard.
2. save game.
3. reload page.
4. load script.
Soon i fix script for another color shemes.

**Comment by qwertgfda** [comment]
Yes, Seem to work fine with white standard.

**Comment by dandcvs** [comment]
Fixed https://github.com/dandcvs/KGAutoPlay/commit/bd97e40872e52e19ae0b0fcd6d5072b998545dbd
