### ISSUE TITLE
Hold Festival used until resources depleted when Carnivals not researched

### ISSUE THREAD

**Issue by dta5003** [dandcvs/KGAutoPlay#10]
I'm seeing "The cultural festival has been extended" repeatedly until it no longer has the resources to do so.  The durations are not stacking, and the resources are being wasted due this behavior happening before Carnivals is researched.

**Comment by dandcvs** [comment]
https://github.com/dandcvs/KGAutoPlay/commit/e9ff67ccbb9db65105615855832e1cccd1300bd9

**Comment by dta5003** [comment]
Looks fixed as far as I can tell, thanks!
