### ISSUE TITLE
Suggestion: blackcoin investment

### ISSUE THREAD

**Issue by YuukyuuKikan** [dandcvs/KGAutoPlay#13]
I have an idea about how to invest blackcoin.
However, I cannot write the code so here's my algorithm.

Enable this by switch or Relic >10K    (100K?)
Record Real-year   (wiki says 13m20s=1 cat year)
When Shatter TC
--If Real-year pass 1y & Levi is here 
--Check bcoin price
--If price < 930 then buy    (900?)
----(or optionally, buy unless it's time to sell)
--If price >1050 then sell   (1080?)
Cycle.

The numbers may not be optimal but I guess it will work.
Thanks for reading and it would be great if you may implement this.

**Comment by dandcvs** [comment]
hi, its already works on 
price > 1099 = sell
price < 900 = buy
if relic value >  1000 + blackcoin value  * 1000
