### ISSUE TITLE
1.4.7.1 - Religion upgrades no longer being purchased

### ISSUE THREAD

**Issue by dta5003** [dandcvs/KGAutoPlay#19]
After resetting and upgrading to 1.4.7.1, I've noticed that Religion upgrades other than Solar Revolution are not being purchased.

**Comment by dta5003** [comment]
Also, Sell Space and Reset is not working.

**Comment by Cissoubaka** [comment]
this is the error in the console : 
```js
kitg.js:108 Uncaught TypeError: gamePage.religion.getFaithBonus is not a function
    at getFaithProdCap (kitg.js:108)
    at autoPraise (kitg.js:123)```

**Comment by Zedsquared** [comment]
Library upgrade to data center also seems to not happen any more. Once manually triggered then data center building goes ahead quite happily and science cap skyrockets nicely.
