### ISSUE TITLE
1 kitten starved to death.

### ISSUE THREAD

**Issue by puggan** [dandcvs/KGAutoPlay#2]
The job management dosn't work, it keept removing the farmers during winter so that the kittens starved.

6 kittens, 109% happiness, 1 karma.

![Screenshot from 2019-05-01 18-54-25](https://user-images.githubusercontent.com/866668/57029697-c6c5bd80-6c42-11e9-892e-8e162a33d60a.png)

**Comment by dandcvs** [comment]
This is a very low level of progress, I started testing the script on 100+ paragon points.

**Comment by puggan** [comment]
If you want to solve/debug it, just open a icognito-window, and run the game for a in-game-year or 2.

Already disabled some functions, and replace other functions, in my copy,
to get around the problems with not having any paragon points yet.

**Comment by dandcvs** [comment]
https://github.com/dandcvs/KGAutoPlay/commit/f0609e3c5bb4df66a9471a5bdb0596a28977b005
i think this can resolve the problem. Up priority to farmer until(paragon point < 100 or  faith solarRevolution.researched == false)
