### ISSUE TITLE
Script immediately buys Hut, making Iron Will impossible to start

### ISSUE THREAD

**Issue by dta5003** [dandcvs/KGAutoPlay#21]
Steps:
1. Reset
2. Pawse game
3. Load KGAutoPlay script

Expected:
4. Switch on Iron Will
5. KGAutoPlay runs, no huts are purchased, Iron Will mode is on
6. Joy

Actual:
4. Immediately upon loading the script, even though the game is paused, a Hut is purchased among other buildings
5. Run is disqualified from Iron Will due to purchasing housing
6. Sadness

Script should not take actions when the game is paused.  Anyone know of a workaround to get into Iron Will?  I'd rather not purposely reset with no Chronospheres and lose out on banked resources just to prevent the purchase of that one Hut.

**Comment by dandcvs** [comment]
Hi, sorry for innactive, you can:
1. Reset.
2. Put "gamePage.ironWill = true" into browser console
3. Load  KGAutoPlay script
4. swith script to Iron Will mode.
