### ISSUE TITLE
Transcension issue

### ISSUE THREAD

**Issue by zweq** [dandcvs/KGAutoPlay#24]
`You have transcended the mortal limits. T-level: NaN`

Result:
Religion bonuses are reset but transcend level is not increased.

**Comment by dandcvs** [comment]
Hi. Can you upload save file with this bug?

**Comment by zweq** [comment]
Sure. You can speed things up by combusting TCs by hand.

[Kittens Game - Run 63 - Year 39525 - Spring, day 52.txt](https://github.com/dandcvs/KGAutoPlay/files/5149318/Kittens.Game.-.Run.63.-.Year.39525.-.Spring.day.52.txt)

**Comment by dandcvs** [comment]
https://github.com/dandcvs/KGAutoPlay/commit/b8f49493c151fc51f46897204ddb5b4d75127b16
