### ISSUE TITLE
Fix priorities on Chronosurge upgrade

### ISSUE THREAD

**Issue by nivensd** [dandcvs/KGAutoPlay#29]
For some reason, the script purchased the Invisible Black Hand upgrade using up the flux I was saving for Chronosurge (which would allow for unpaused flux generation). I probably should have killed the script but I wasn't thinking about it and it doesn't make sense to me why that would be prioritized when the script already handles blackcoin purchase/sale.

**Comment by dandcvs** [comment]
https://github.com/dandcvs/KGAutoPlay/commit/c18f568a125ae562cba5447d825ff325f4a8d880
