### ISSUE TITLE
Since game got updated the script doesn't praise the sun anymore. 

### ISSUE THREAD

**Issue by qwertgfda** [dandcvs/KGAutoPlay#3]
Se topic: Since game got updated the script doesn't praise the sun anymore.

**Comment by qwertgfda** [comment]
This might not be an issue, after I restarted my computer it seems it praising again. Might be the latest change in the game version or something else, before I saw it sit at max all the time.

**Comment by qwertgfda** [comment]
looks like it still sometimes still parise the sun, but lot of the time it sit at the max.

**Comment by dandcvs** [comment]
This is bug in: Ver 1.4.6.0.b 
resurs value <> resurs maxvalue like:
("faith").value = 16867677.45  and ("faith").maxValue = 16867930.96,
but  ingame this values = (faith 16.868M	/16.868M)
https://github.com/dandcvs/KGAutoPlay/commit/1f5cf40e88f1112f3c4e9d04c62b2a8c279d24d7

**Comment by KeySer87** [comment]
Thanks, SEems to work fine again now.
