### ISSUE TITLE
Suggestion: skip "Oil Refinery" upgrade for now

### ISSUE THREAD

**Issue by YuukyuuKikan** [dandcvs/KGAutoPlay#4]
This upgrade will cause BioLab to consume electricity.
Since the science cap is cut off, it is very important to keep the labs active for a higher science cap.
Without this upgrade, biolabs are still functioning and big bunch of electricity can be saved. The only loss is oil which is not important in most of the cases.

Thanks for reading.

**Comment by dandcvs** [comment]
Ok, lets test it. Upgrade id = biofuel not Oil Refinery.

**Comment by YuukyuuKikan** [comment]
> Ok, lets test it. Upgrade id = biofuel not Oil Refinery.

Ooops, my mistake. Yes, I mean "Biofuel Processing". Thanks for your upgrade.
