### ISSUE TITLE
Suggestion: Better Time Crystal Management Controls

### ISSUE THREAD

**Issue by Cellidor** [dandcvs/KGAutoPlay#6]
During the transition between mid to late game, saving up time crystals is crucial. By using 100 TC per cycle combined with autoplay I can reset and build up paragon fast every few hours. Problem is, if I try and save up TC, it'll automatically shatter them all as fast as it can. I'll have over 1000 saved up ready for some rapid-fire resets only to find all the crystals gone soon after I started up. Being able to toggle shattering/purchasing with those would be good, primarily because of how long it takes to obtain them.

**Comment by dandcvs** [comment]
Hi, KGAutoPlay option menu in the bottom right "footer" links contains button "CollectResBReset", if button active,  script saving late game res(Tcrystal, Relic, Void). Only science and workshop upgrades can use this resources. Scrip always shatter tc while not redmoon cycle active. shatter tc whith x45 and black piramid >0 almost always can rise leviathans duration.
if resources are spent for any other reason, then this is a bug.
